### ISSUE TITLE
I found sth. wrong when I'm running, brother do you know how to solve this problem

### ISSUE THREAD

**Issue by p1gz** [Damian89/extended-ssrf-search#11]
C:\Users\msi-\Desktop\extended-ssrf-search-master>python3 extended-ssrf-search.py
Traceback (most recent call last):
  File "extended-ssrf-search.py", line 84, in <module>
    main()
  File "extended-ssrf-search.py", line 38, in main
    config = Config()
  File "C:\Users\msi-\Desktop\extended-ssrf-search-master\inc\Config.py", line 33, in __init__
    self.__set_set_config()
  File "C:\Users\msi-\Desktop\extended-ssrf-search-master\inc\Config.py", line 48, in __set_set_config
    self.callback = self.config["default"]["CallbackHost"]
  File "D:\python3\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'default'

**Comment by Damian89** [comment]
See error... callback host not set!
