### ISSUE TITLE
error at running script

### ISSUE THREAD

**Issue by xyele** [Damian89/extended-ssrf-search#3]
```
root@kali:~/extended-ssrf-search# ls
app-setting.conf  config  extended-ssrf-search.py  inc  README.md
root@kali:~/extended-ssrf-search# python3 extended-ssrf-search.py
Traceback (most recent call last):
  File "extended-ssrf-search.py", line 84, in <module>
    main()
  File "extended-ssrf-search.py", line 38, in main
    config = Config()
  File "/root/extended-ssrf-search/inc/Config.py", line 33, in __init__
    self.__set_set_config()
  File "/root/extended-ssrf-search/inc/Config.py", line 48, in __set_set_config
    self.callback = self.config["default"]["CallbackHost"]
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'default'
root@kali:~/extended-ssrf-search#

```

my py version is 3.7.3rc1

**Comment by Damian89** [comment]
Did you read the doc? How does your app-setting.conf look like?

**Comment by xyele** [comment]
yes i read most part of doc. 

the callbackhost on config file is like x.burpcollaborator.net

**Comment by xyele** [comment]
oh okey i solved the problem.

the name of settings file should be app-settings.conf not app-setting.conf.
i guess you should change it on doc.

thank you mate
